### ISSUE TITLE
subject translations

### ISSUE THREAD

**Issue by keilmillerjr** [ryanb/letter_opener#87]
Any reason why this wouldn't work? Am I doing this correctly, or is it a bug? I'm trying to make my existing and working mailer to work with i18n translations.

``` ruby
# snippet from message_mailer.rb
mail to: ENV['MAILER_USERNAME'], subject: t('message_mailer.new_message', message: @message.name), css: ['mailers/message']
```

``` yaml
# snippet from en.yml
en
  message_mailer:
    new_message:
      subject: "New message from %{name}"
```

And the rendered mailer shows a subject like so:

```
Subject:
{:subject=>"New message from %{name}"}
```

EDIT: I changed the config from letter_opener to smtp, and this does not seem to be an issue with letter_opener. The actual emails to my inbox reflect the same results as letter_opener. Can anyone help me figure out what I am doing wrong anyways?
